# Generated by Django 5.1.4 on 2025-07-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatepet',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
