# Generated by Django 5.1.4 on 2025-07-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0008_feedback_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comment',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.AddField(
            model_name='feedback',
            name='role',
            field=models.CharField(default='Pet Adopter', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='feedback_images/'),
            preserve_default=False,
        ),
    ]
